In [2]:
# Syntax open: open(file, mode= 'r', buffering=-1, etc)
# mode: r (read), w(write), a (append)
f = open('agencies.txt', 'r')    
fw = open('agencies_write.txt', 'w')
# read all the context to a list
lines = f.readlines()
for li in lines:
    write_lines = fw.writelines(li)
    print(li.strip())

f.close()
fw.close()

Federal Bureau of Investigation
Central Intelligence Agency
The Triboro Bridge and Tunnel Authority
Housing and Urban Development
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [3]:
f = open('agencies.txt', 'r')   # Chậm hơn nhưng ko tốn bộ nhớ.
# read context line by line
for line in f:
    if 'authority' in line.lower():
        print(line.strip())
f.close()

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [4]:
# Read author.txt, print name & email
f = open('authors.txt', 'r')
# Skip 3 first lines
for _ in range(3):
    next(f)

# TODO: split line to get name & email
for line in f:
    name, email = line.split('<')
    name = name.strip() + ':'
    email = email.strip()[:-1]
    print(f'{name:25}{email:25}')

Paul Bakaus:             paul.bakaus@gmail.com    
Richard Worth:           rdworth@gmail.com        
Yehuda Katz:             wycats@gmail.com         
Sean Catchpole:          sean@sunsean.com         
John Resig:              jeresig@gmail.com        
Tane Piper:              piper.tane@gmail.com     
Dmitri Gaskin:           dmitrig01@gmail.com      
Klaus Hartl:             klaus.hartl@gmail.com    
Stefan Petre:            stefan.petre@gmail.com   
Gilles van den Hoven:    gilles@webunity.nl       
Micheil Bryan Smith:     micheil@brandedcode.com  
Jörn Zaefferer:         joern.zaefferer@gmail.com
Marc Grabanski:          m@marcgrabanski.com      
Keith Wood:              kbwood@iinet.com.au      
Brandon Aaron:           brandon.aaron@gmail.com  
Scott González:         scott.gonzalez@gmail.com 
Eduardo Lundgren:        eduardolundgren@gmail.com
Aaron Eisenberger:       aaronchi@gmail.com       
Joan Piedra:             theneojp@gmail.com       
Bruno Basto:             b.bast

In [5]:
import numpy as np
data = np.loadtxt('falling.txt', skiprows = 5)
print(data)


[[  0.    0.  180.    3.5]
 [  1.    0.5 185.    4.5]
 [  2.    0.7 192.    5.2]]


In [6]:
times = data[:, 1]
print(times)
heights = data[:, 2]
print(heights)

[0.  0.5 0.7]
[180. 185. 192.]


In [7]:
times, heights = np.loadtxt('falling.txt', skiprows=5, usecols=(1, 2), unpack=True)
print(times)
print(heights)

[0.  0.5 0.7]
[180. 185. 192.]


In [8]:
student_data = np.loadtxt('gradebook.csv', delimiter=',', skiprows=1,dtype=str)
#Clean std data
for student in student_data:
    if student[4] == '':
        student[4] = '0'
    if float(student[4]) > 10:
        student[4] = '10'
    if student[2] == '':
        student[2] = 'GCH22000'

#Print std data
# for student in student_data:
#     if float(student[4]) >= 6.5:
#         print(f'{student[2]:10}{student[3]:20}{student[4]:10}')
pass_students = [['Login', 'Email', 'Code', 'Name', 'Grade']]
pass_students += [student for student in student_data if float(student[4]) >=6.5]
for st in pass_students:
    print(f'{st[2]:10}{st[3]:20}{st[4]:10}')

#Write to file 
np.savetxt('pass_student.csv', pass_students, delimiter=',', fmt='%s')


Code      Name                Grade     
GBH17538  Le Minh Huong       6.5       
GCH16336  Nguyen The Dat      6.5       
GCH16388  Pham Minh Thang     9.5       
GCH16573  Do Duy Tung         6.5       
GCH16603  Nguyen Thanh Thang  8.0       
GCH22000  Nguyen Minh Tuan    10        


In [9]:
codes, names, grades = np.loadtxt('gradebook.csv', delimiter=',', skiprows=1,
                                  usecols=(2,3,4), dtype=str, unpack=True)

for i in range(len(codes)):
    if grades[i] == '':
        grades[i] = '0'
    if codes[i] == '':
        codes[i] = 'GCH22000'
    if float(grades[i]) > 10:
        grades[i] = '10'

# for i in range(len(codes)):
#     if float(grades[i]) >= 6.5:
#         print(f'{codes[i]:10}{names[i]:20}{grades[i]:10}')

# Save clean data into new file
np.savetxt('clean_gradebook.csv', np.column_stack((codes, names, grades)), delimiter=',', fmt='%s', header = 'Code, Name, Grade')
print('Done!')

Done!


In [10]:
import csv

# Tốn ít bộ nhớ hơn cái trên, nhưng chạy chậm hơn.
with open('gradebook.csv', 'r') as f:   #tranh viec quen close
    reader = csv.reader(f) # -> Tương tự như cái generator
    fw = open('pass_std.csv', 'w')
    writer = csv.writer(fw)

    writer.writerow(next(reader)) # write header

    # next(reader) #skip header
    for row in reader:
        if row[4] == '':
            row[4] = '0'
        if row[2] == '':
            row[2] = 'GCH22000'
        if float(row[4]) > 10:
            row[4] = '10'
        if float(row[4]) >= 6.5:
            # print(f'{row[2]:10}{rows[3]:20}{rows[4]:10}')
            writer.writerow(row)
    fw.close()
print('Done!')
    

Done!


In [11]:
# Clean pizza_data.csv
f = open('pizza_data.csv', 'r')
reader = csv.reader(f)

# Remove id header, url header
header = next(reader)
del header[0]
del header[7]

fw = open('clean_pizza_data.csv', 'w', encoding='utf-8')
writer = csv.writer(fw)
writer.writerow(header)

for row in reader: 
    # Remove rows that have empty menus.amountMax, menus.amountMin
    if row[9] == '' or row[10] == '':
        continue

    # Rows that have empty priceRangeMax, priceRangeMin ->set to 0
    row[18] = '0' if row[18] == '' else row[18]
    row[19] = '0' if row[19] == '' else row[19]

    # For row that has more than one categories, keep just the 1st one
    row[2] = row[2].split(',')[0]

    # Remove id column, url column
    del row[0]
    del row[7]

    writer.writerow(row)

print('Done!')
f.close()
fw.close()

Done!
