In [1]:
products = ['pencil', 'eraser', 'ruler', 'pen', 'notebook']
prices = [1000, 500, 2000, 5000, 10000]
sold = [120, 1000, 80, 50, 30]
# 120 000, 500 000, 160 000, 250 000, 300 000

# Find product that has the highest sold
max_sold = prices[0] * sold[0]
i_max = 0
n = len(products)
for i in range(1, n):
    if prices[i] * sold[i] > max_sold:
        max_sold = prices[i] * sold[i]
        i_max = i
    
print(f'{products[i_max]} has the highest sold: {max_sold}')

# Find product that has the lowest sold
lowest_sold = prices[0] * sold[0]
i_lowest = 0
for i in range(1, n):
    if prices[i] * sold[i] < lowest_sold:
        lowest_sold = prices[i] * sold[i]
        i_lowest = i
    
print(f'{products[i_lowest]} has the lowest sold: {lowest_sold}')

# Find product that has the highest price
# Find product that has the lowest price
i_highest_price = 0
i_lowest_price = 0
highest_price = prices[0]
lowest_price = prices[0]
for i in range(1, n):
    if prices[i] > highest_price:
        highest_price = prices[i]
        i_highest_price = i
    else:
        lowest_price = prices[i]
        i_lowest_price = i

print(f'{products[i_highest_price]} has the highest price: {highest_price}')
print(f'{products[i_lowest_price]} has the lowest price: {lowest_price}')

# Find product that has sold the most
# Find product that has sold the least
i_sm = 0
i_sl = 0
most_sold = sold[0]
least_sold = sold[0]
for i in range(1, n):
    if sold[i] > most_sold:
        most_sold = sold[i]
        i_sm = i
    else:
        least_sold = sold[i]
        i_sl = i

print(f'{products[i_sm]} has sold the most: {most_sold}')
print(f'{products[i_sl]} has sold the least: {least_sold}')


eraser has the highest sold: 500000
pencil has the lowest sold: 120000
notebook has the highest price: 10000
eraser has the lowest price: 500
eraser has sold the most: 1000
notebook has sold the least: 30


In [2]:
products_sold = [['pencil', 1000, 120],
                 ['eraser', 500, 1000],
                 ['ruler', 2000, 80],
                 ['pen', 5000, 50],
                 ['notebook', 10000, 30]]

In [3]:
max_sold = products_sold[0][1] * products_sold[0][2]
lowest_sold = products_sold[0][1] * products_sold[0][2]
highest_price = products_sold[0][1]
lowest_price = products_sold[0][1]
most_sold = products_sold[0][2]
least_sold = products_sold[0][2]
i_max = 0 
i_lowest = 0
i_highest_price = 0
i_lowest_price = 0
i_sm = 0
i_sl = 0
n = len(products_sold)

for i in range(1, n):
    if products_sold[i][1] * products_sold[i][2] > max_sold:
        max_sold = products_sold[i][1] * products_sold[i][2]
        i_max = i
    elif products_sold[i][1] * products_sold[i][2] < lowest_sold:
        lowest_sold = products_sold[i][1] * products_sold[i][2]
        i_lowest = i
    if products_sold[i][1] > highest_price:
        highest_price = products_sold[i][1]
        i_highest_price = i
    else:
        lowest_price = products_sold[i][1]
        i_lowest_price = i
    if products_sold[i][2] > most_sold:
        most_sold = products_sold[i][2]
        i_sm = i
    else:
        least_sold = products_sold[i][2]
        i_sl = i

print(f'{products_sold[i_max][0]} has the highest sold: {max_sold}')
print(f'{products_sold[i_lowest][0]} has the lowest sold: {lowest_sold}')
print(f'{products_sold[i_highest_price][0]} has the highest price: {highest_price}')
print(f'{products_sold[i_lowest_price][0]} has the lowest price: {lowest_price}')
print(f'{products_sold[i_sm][0]} has sold the most: {most_sold}')
print(f'{products_sold[i_sl][0]} has sold the least: {least_sold}')

eraser has the highest sold: 500000
pencil has the lowest sold: 120000
notebook has the highest price: 10000
eraser has the lowest price: 500
eraser has sold the most: 1000
notebook has sold the least: 30


In [25]:
import random as rd
number = [rd.sample(range(100),5),
          rd.sample(range(100),5),
          rd.sample(range(100),5),
          rd.sample(range(100),5),
          rd.sample(range(100),5)]
print(number)


[[22, 47, 55, 69, 2], [70, 33, 81, 39, 57], [26, 17, 29, 24, 87], [45, 17, 50, 51, 49], [29, 94, 87, 31, 86]]
<class 'list'>


In [5]:
# Get 3 middle rows in as many ways as you can
middle =  number[1:4]
middle2 =  number[1:-1]
middle3 =  number[-4:-1]
middle4 =  number[-4:4]
print(middle)
print(middle2)
print(middle3)
print(middle4)


[[6, 73, 54, 2, 32], [51, 4, 42, 14, 28], [33, 89, 40, 38, 10]]
[[6, 73, 54, 2, 32], [51, 4, 42, 14, 28], [33, 89, 40, 38, 10]]
[[6, 73, 54, 2, 32], [51, 4, 42, 14, 28], [33, 89, 40, 38, 10]]
[[6, 73, 54, 2, 32], [51, 4, 42, 14, 28], [33, 89, 40, 38, 10]]


In [6]:
# Get 2 last rows in as many ways as you can
last1 =  number[3:]
last4 =  number[-2:]
print(last1)
print(last4)

[[33, 89, 40, 38, 10], [80, 36, 56, 58, 52]]
[[33, 89, 40, 38, 10], [80, 36, 56, 58, 52]]


In [7]:
n = int(input('Enter n: '))
print(f'Max of row {n}: {max(number[n])}')
print(f'Min of row {n}: {min(number[n])}')
print(f'Sum of row {n}: {sum(number[n])}')

Max of row 2: 51
Min of row 2: 4
Sum of row 2: 139


In [2]:
import numpy as np
number = np.array([1,2,3,4,5])
print(number, type(number))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
a = [1,2.3,'hello',True]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2.3, 'hello', True] <class 'list'>
['1' '2.3' 'hello' 'True'] <class 'numpy.ndarray'>


In [10]:
a = list(range(1,11))
print(a)
b = np.arange(1,11)  # Full syntax arange; np.arange(start, stop, step)
print(b)
print(np.arange(10))
print(np.arange(1,20,2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [4]:
#  Function linspace: np.linspace(start, stop, num, endpoint)
print(np.linspace(1, 10, 10, dtype=int))
print(np.linspace(0, 10, 10, endpoint=False, dtype=int))
print(np.linspace(1, 19, 10, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
print(np.arange(0, 10, 0.5))
print(np.linspace(0, 10, 20, endpoint=False))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [7]:
# function logspace: np.logspace(start, stop, num, endpoint= , base = 2)
a = np.linspace(1, 10, 10, endpoint=True, dtype=int)
b = 2**a
print(a)
print(b)
print(np.logspace(1, 10, 10, endpoint=True, base=2, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]
[   2    4    8   16   32   64  128  256  512 1024]
[   2    4    8   16   32   64  128  256  512 1024]


In [14]:
# Generate following numbers using logspace
# 1 3 9 27 81 243
print(np.logspace(0, 5, 6, base = 3, endpoint=True, dtype = int))
# 10 100 1000 10000 100000 1000000
print(np.logspace(1, 6, 6, endpoint=True, dtype=int))


[  1   3   9  27  81 243]
[     10     100    1000   10000  100000 1000000]


In [15]:
zeros = np.zeros(10, dtype=int)
ones = np.ones(10,dtype=int)
print(zeros)
print(ones)
print(ones*2)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [16]:
# Array operators: +, -, *, /, //, %, **
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a // 2)
print(a % 2)
print(a ** 2)

[ 3  4  5  6  7  8  9 10 11 12]
[-1  0  1  2  3  4  5  6  7  8]
[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[0 1 1 2 2 3 3 4 4 5]
[1 0 1 0 1 0 1 0 1 0]
[  1   4   9  16  25  36  49  64  81 100]


In [17]:
# Genarate 10 radom numbers in range [0, 99]
number = np.random.randint(0, 100, 10)
print(number)
b = number % 2
print(b)
c = b == 0
print(c)
evens = number[c] # boolean indexing

[ 5 29 98 13 21  6 43 65 12  8]
[1 1 0 1 1 0 1 1 0 0]
[False False  True False False  True False False  True  True]


In [18]:
print(evens)
odds = number[number % 2 != 0]
print(odds)

[98  6 12  8]
[ 5 29 13 21 43 65]


In [19]:
numbers = np.random.randint(-99, 100, 20)
print(numbers)
# Find all positive numbers
print(number[number>0])
# Find all negative numbers
print(numbers[numbers<0])

[-76  96   8 -64 -66  20 -13  83 -85  98 -79 -32  58  52 -37  30  12 -39
 -95 -66]
[ 5 29 98 13 21  6 43 65 12  8]
[-76 -64 -66 -13 -85 -79 -32 -37 -39 -95 -66]


In [20]:
numbers[numbers<0] = 0
print(numbers)

[ 0 96  8  0  0 20  0 83  0 98  0  0 58 52  0 30 12  0  0  0]


In [21]:
def check(arr, brr):
    arr[arr == ''] = 'John Doe'
    brr[brr < 0] = 0
    brr[brr > 150] = 150
    print(arr)
    print(brr)

In [22]:
names = np.array(['Barrack Obama', 'Donald Trump', '', 'Joe Biden', 'Hillary Clintion'])
ages = np.array([59, 74, 78, -10, 272])

# names[names == ''] = 'John Doe'
# ages[ages < 0] = 0
# ages[ages > 150] = 150

# print(names)
# print(ages)

check(names, ages)

['Barrack Obama' 'Donald Trump' 'John Doe' 'Joe Biden' 'Hillary Clintion']
[ 59  74  78   0 150]


In [23]:
print(f'Min age = {min(ages)}')
print(f'Max age = {max(ages)}')
print(f'Longest name: {max(names, key=len)}')
print(f'Shortest name: {min(names, key=len)}')

Min age = 0
Max age = 150
Longest name: Hillary Clintion
Shortest name: John Doe
