In [5]:
import numpy as np
y = np.array([0., 1.3, 5., 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1., 1.5, 2.08, 2.55, 3.2])
v = np.zeros(7)
print(v)

n = len(y)
for i in range(n):
    v[i] = (y[i] - y[i-1])/(t[i] - t[i-1])
    # print(y[i-1], y[i], t[i], t[i-1])

print(v)


[0. 0. 0. 0. 0. 0. 0.]
40.0 0.0 0.0 3.2
0.0 1.3 0.49 0.0
1.3 5.0 1.0 0.49
5.0 10.9 1.5 1.0
10.9 18.9 2.08 1.5
18.9 28.7 2.55 2.08
28.7 40.0 3.2 2.55
[12.5         2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [2]:
v[1:] = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[12.5         2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [3]:
# 2D arrays
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)
b = np.reshape(a, (2, 3)) #Convert 1D array to 2D array 2x3
print(b, b.shape)

[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [4]:
a = np.zeros((2, 3), dtype=int)
print(a)
a = np.linspace(0, 1, 6) #Return 6 evenly spaced numbers over the interval [0, 1]
b = np.reshape(a, (2, 3))
print(b)

[[0 0 0]
 [0 0 0]]
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


In [7]:
a = np.random.randint(10, 100, (4, 4))
print(a)

[[17 76 81 20]
 [41 81 56 11]
 [95 14 71 28]
 [31 60 27 53]]


In [10]:
print(a[1][2], a[1, 2])
print(a[1:3, :])
print(a[:2, 1:3])

56 56
[[41 81 56 11]
 [95 14 71 28]]
[[76 81]
 [81 56]]


In [7]:
a = np.random.randint(1, 100, (6, 6))
print(a)

[[97  3 45 24 87 33]
 [ 2 66 49 93  6 94]
 [13 98 36  2 34 52]
 [90 37 58 86 25 95]
 [89 45 71 50 27  3]
 [58 56 95  3 30 61]]


In [8]:
print(a[:, :1])
print("----------------------")
print(a[:2, 3:])
print("----------------------")
print(a[1:4, 2:-1])
print("----------------------")
print(a[3:, 3:])

[[97]
 [ 2]
 [13]
 [90]
 [89]
 [58]]
----------------------
[[24 87 33]
 [93  6 94]]
----------------------
[[49 93  6]
 [36  2 34]
 [58 86 25]]
----------------------
[[86 25 95]
 [50 27  3]
 [ 3 30 61]]


In [9]:
a[0] = 0
a[2:4, 3:-1] = 0
print(a)

[[ 0  0  0  0  0  0]
 [ 2 66 49 93  6 94]
 [13 98 36  0  0 52]
 [90 37 58  0  0 95]
 [89 45 71 50 27  3]
 [58 56 95  3 30 61]]


In [22]:
a = np.ones((8, 8), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [12]:
a = np.ones((8, 8), dtype=int)
a[::2,::2] = 0
a[1::2,1::2] = 0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
a = np.random.randint(10, 100, (8, 8))
a[a%3 == 0] = a[a%3 == 0]*-1
print(a)

[[ 20  79  55 -24  68  40 -63  32]
 [ 89 -18  29  55  26  92  85  97]
 [ 19  23  53 -39  11  71  16  61]
 [ 98  83  40 -51  64 -12 -75 -45]
 [-87  76  94  92  95  23  77  19]
 [ 64  98  16 -69 -69 -36  17 -30]
 [-87  10  37 -24 -36 -42  92  64]
 [-84  28  29 -21  49  98 -60  62]]


In [39]:
print(a[:4, :4])
print(a[:4, 4:])
print(a[4:, :4])
print(a[4:, 4:])
b = a[4:, 4:]

[[ 20  79  55 -24]
 [ 89 -18  29  55]
 [ 19  23  53 -39]
 [ 98  83  40 -51]]
[[ 68  40 -63  32]
 [ 26  92  85  97]
 [ 11  71  16  61]
 [ 64 -12 -75 -45]]
[[-87  76  94  92]
 [ 64  98  16 -69]
 [-87  10  37 -24]
 [-84  28  29 -21]]
[[ 95  23  77  19]
 [-69 -36  17 -30]
 [-36 -42  92  64]
 [ 49  98 -60  62]]


In [40]:
print(b.size, b.shape, np.mean(b), np.std(b))

16 (4, 4) 20.1875 56.81023097779131
